export const contact = [
  {
    id: 0,
    titel: "Kostenloser HTML & CSS Workshop für Einsteiger:innen",
    datum: "15.April 2020",
    beschreibung: "Bleib nicht stumm! Lerne deine ersten Sätze in HTML und CSS",
    image: "../Bild1-neu.png",
    überschrift1: "### In unserem kostenlosen 3 stündigen Workshop lernst du:",
    detail1a: "- Grundlagen zum Thema Web-Entwicklung",
    detail1b: "- Übersicht der gängigsten Programmiersprachen",
    detail1c: "- Grundlagen im Bereich HTML & CSS",
    überschrift2: "### Ziele des Workshops:",
    detail2a: "- Du weißt was Web-Entwicklung bedeutet",
    detail2b: "- Du kannst Web-Entwicklung von anderen  IT Berufen abgrenzen",
    detail2c: "- Du kennst die Grundlagen von HTML und CSS",
    detail2d: "- Du kannst eine kleine eigene Webseite erstellen!! ",
    trainer: "### Trainer / Workshop Leiter:",
    trainer1: "- Eric Noack (SuperCode - Trainer)",
    trainer2: "- Maher Alhallak (SuperCode - Assistant Trainer)",
    trainer3: "- Sérgio Cardeal (SuperCode – Geschäftsführer)",
    überschrift3: "### Anmeldung, Tickets und Gebühr:",
    detail3:
      "Die Tickets/Plätze sind stark limitiert – wer Interesse hat sollte sich also schnell anmelden.",
    überschrift4: "### Technik & Verpflegung",
    detail4: "Bring your own Laptop, Snacks und Drinks stellen wir",
    überschrift5: "Der Workshop wird durch einen unserer Partner durchgeführt:",
    detail5:
      "Super(Code) - digitale Bildung für Alle. Ein modernes, gemeinwohlorientiertes und AZAV zertifiziertes Bildungsinstitut für den Bereich Webentwicklung und IoT in Düsseldorf.",
  },
  {
    id: 1,
    titel: "Bitkomm Studie zum Fachkräftemangel 2020",
    datum: "21.April 2020",
    beschreibung:
      "Bleib nicht stumm! Lerne deine ersten Sätze in HTML und CSS(...)",
    image: "../Bild2-neu.png",
    überschrift1: "### In unserem kostenlosen 3 stündigen Workshop lernst du:",
    detail1a: "- Grundlagen zum Thema Web-Entwicklung",
    detail1b: "- Übersicht der gängigsten Programmiersprachen",
    detail1c: "- Grundlagen im Bereich HTML & CSS",
    überschrift2: "### Ziele des Workshops:",
    detail2a: "- Du weißt was Web-Entwicklung bedeutet",
    detail2b: "- Du kannst Web-Entwicklung von anderen  IT Berufen abgrenzen",
    detail2c: "- Du kennst die Grundlagen von HTML und CSS",
    detail2d: "- Du kannst eine kleine eigene Webseite erstellen!! ",
    trainer: "### Trainer / Workshop Leiter:",
    trainer1: "- Eric Noack (SuperCode - Trainer)",
    trainer2: "- Maher Alhallak (SuperCode - Assistant Trainer)",
    trainer3: "- Sérgio Cardeal (SuperCode – Geschäftsführer)",
    überschrift3: "### Anmeldung, Tickets und Gebühr:",
    detail3:
      "Die Tickets/Plätze sind stark limitiert – wer Interesse hat sollte sich also schnell anmelden.",
    überschrift4: "### Technik & Verpflegung",
    detail4: "Bring your own Laptop, Snacks und Drinks stellen wir",
    überschrift5: "Der Workshop wird durch einen unserer Partner durchgeführt:",
    detail5:
      "Super(Code) - digitale Bildung für Alle. Ein modernes, gemeinwohlorientiertes und AZAV zertifiziertes Bildungsinstitut für den Bereich Webentwicklung und IoT in Düsseldorf.",
  },
  {
    id: 2,
    titel: "Better Place – Digitale Wege der Integration",
    datum: "26.April 2020",
    beschreibung:
      "Wir sind dabei - du auch? Fe:male Hackaton from Fe:male Innovation Hub@Sipgate(...)",
    image: "../Bild3-neu.png",
    überschrift1: "### In unserem kostenlosen 3 stündigen Workshop lernst du:",
    detail1a: "- Grundlagen zum Thema Web-Entwicklung",
    detail1b: "- Übersicht der gängigsten Programmiersprachen",
    detail1c: "- Grundlagen im Bereich HTML & CSS",
    überschrift2: "### Ziele des Workshops:",
    detail2a: "- Du weißt was Web-Entwicklung bedeutet",
    detail2b: "- Du kannst Web-Entwicklung von anderen  IT Berufen abgrenzen",
    detail2c: "- Du kennst die Grundlagen von HTML und CSS",
    detail2d: "- Du kannst eine kleine eigene Webseite erstellen!! ",
    trainer: "### Trainer / Workshop Leiter:",
    trainer1: "- Eric Noack (SuperCode - Trainer)",
    trainer2: "- Maher Alhallak (SuperCode - Assistant Trainer)",
    trainer3: "- Sérgio Cardeal (SuperCode – Geschäftsführer)",
    überschrift3: "### Anmeldung, Tickets und Gebühr:",
    detail3:
      "Die Tickets/Plätze sind stark limitiert – wer Interesse hat sollte sich also schnell anmelden.",
    überschrift4: "### Technik & Verpflegung",
    detail4: "Bring your own Laptop, Snacks und Drinks stellen wir",
    überschrift5: "Der Workshop wird durch einen unserer Partner durchgeführt:",
    detail5:
      "Super(Code) - digitale Bildung für Alle. Ein modernes, gemeinwohlorientiertes und AZAV zertifiziertes Bildungsinstitut für den Bereich Webentwicklung und IoT in Düsseldorf.",
  },
  {
    id: 3,
    titel: "Agile goes Non-Profit",
    datum: "28.April 2020",
    beschreibung:
      "Welche Bildung brauchen wir und in was wollen wir uns bilden? Ein Kongress, gemeinsam mit(...)",
    image: "../Bild4-neu.png",
    überschrift1: "### In unserem kostenlosen 3 stündigen Workshop lernst du:",
    detail1a: "- Grundlagen zum Thema Web-Entwicklung",
    detail1b: "- Übersicht der gängigsten Programmiersprachen",
    detail1c: "- Grundlagen im Bereich HTML & CSS",
    überschrift2: "### Ziele des Workshops:",
    detail2a: "- Du weißt was Web-Entwicklung bedeutet",
    detail2b: "- Du kannst Web-Entwicklung von anderen  IT Berufen abgrenzen",
    detail2c: "- Du kennst die Grundlagen von HTML und CSS",
    detail2d: "- Du kannst eine kleine eigene Webseite erstellen!! ",
    trainer: "### Trainer / Workshop Leiter:",
    trainer1: "- Eric Noack (SuperCode - Trainer)",
    trainer2: "- Maher Alhallak (SuperCode - Assistant Trainer)",
    trainer3: "- Sérgio Cardeal (SuperCode – Geschäftsführer)",
    überschrift3: "### Anmeldung, Tickets und Gebühr:",
    detail3:
      "Die Tickets/Plätze sind stark limitiert – wer Interesse hat sollte sich also schnell anmelden.",
    überschrift4: "### Technik & Verpflegung",
    detail4: "Bring your own Laptop, Snacks und Drinks stellen wir",
    überschrift5: "Der Workshop wird durch einen unserer Partner durchgeführt:",
    detail5:
      "Super(Code) - digitale Bildung für Alle. Ein modernes, gemeinwohlorientiertes und AZAV zertifiziertes Bildungsinstitut für den Bereich Webentwicklung und IoT in Düsseldorf.",
  },
];
